const products = [
  {
    id: 1,
    name: "Faded Grandeur Stud Earrings",
    price: "$52.00",
    image: "/home/new_r.jpeg",
    image_hover: "/home/model_r.jpg",
    likes: 117,
    views: "10.4k",
  },
  {
    id: 2,
    name: "Faded Grandeur Stud Earrings",
    price: "$52.00",
    image: "/home/new_r.jpeg",
    image_hover: "/home/model_r.jpg",
    likes: 117,
    views: "10.4k",
  },
  {
    id: 3,
    name: "Faded Grandeur Stud Earrings",
    price: "$52.00",
    image: "/home/new_r.jpeg",
    image_hover: "/home/model_r.jpg",
    likes: 117,
    views: "10.4k",
  },
  {
    id: 4,
    name: "Faded Grandeur Stud Earrings",
    price: "$52.00",
    image: "/home/new_r.jpeg",
    image_hover: "/home/model_r.jpg",
    likes: 117,
    views: "10.4k",
  },
  {
    id: 5,
    name: "Faded Grandeur Stud Earrings",
    price: "$52.00",
    image: "/home/new_r.jpeg",
    image_hover: "/home/model_r.jpg",
    likes: 117,
    views: "10.4k",
  },
  {
    id: 6,
    name: "Faded Grandeur Stud Earrings",
    price: "$52.00",
    image: "/home/bridal.jpeg",
    image_hover: "/home/best.jpeg",
    likes: 117,
    views: "10.4k",
  },
  {
    id: 7,
    name: "Faded Grandeur Stud Earrings",
    price: "$52.00",
    image: "/home/bridal.jpeg",
    image_hover: "/home/best.jpeg",
    likes: 117,
    views: "10.4k",
  },
  {
    id: 8,
    name: "Faded Grandeur Stud Earrings",
    price: "$52.00",
    image: "/home/bridal.jpeg",
    image_hover: "/home/best.jpeg",
    likes: 117,
    views: "10.4k",
  },
];

export default products;
